export enum ErrorCode {
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INTERNAL_SERVER_ERROR = 'INTERNALE_SERVER_ERROR',
  REVIEW_NOT_FOUND = 'REVIEW_NOT_FOUND',
  REVIEW_DELETE_FORBIDDEN = 'REVIEW_DELETE_FORBIDDEN',
  FORBIDDEN = 'FORBIDDEN',
}
